# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development: &development
  secret_key_base: 41701ed7d215b4cc3deca5ef65838d0dbac30ec72ddcc83ed7dd566cd9554d20103a6fc89d97c6d556fbd3c11e6937bc93cc296a3703686f8352c4eaffbdab23
  facebook:
    app_id: "1176625625688117"
    app_secret: "a28a3d5fd3257389e60eb6d5c1cb3530"

test: 
  <<: *development
  secret_key_base: 75bb7bc7e100ab819b3bebd48dcfba60afe060ba4a15b510ed0599ad1b3eee70064fa114cce315128bb9e83661fb784ab65a9840310814d100f40fff195f2792

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *development
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
